name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build_wasm_wheel:
    name: Build wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pyodide-build

      - name: Determine pyodide Emscripten version
        run: |
          PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          echo "pyodide-emscripten-version=$PYODIDE_EMSCRIPTEN_VERSION" >> $GITHUB_ENV

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v13
        with:
          version: ${{ env.pyodide-emscripten-version }}

      - name: Build dependencies
        run: ./bin/build_dependencies_wasm.sh

      - name: Build wheel
        run: pyodide build --exports whole_archive

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl
